# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
import time
import tools


start_time = time.time()
start_number = 286
flag = True
while flag:
    t_number = int(start_number * (start_number + 1) / 2)
    if tools.is_pentagon_number(t_number) and tools.is_hexagonal_number(t_number):
        print(start_number, t_number)
        flag = False
    start_number += 1
print('result is ', '')
print('total time is ', time.time() - start_time, 'ms')